# BIN=prog
# auto:
# 	gcc -fopenmp -lm auto.c -o ${BIN}
# manual:
# 	gcc -fopenmp -lm manual.c -o ${BIN}
# seq:
# 	gcc -fopenmp -lm seq.c -o ${BIN}

all:
# 	g++ -O3 auto.cpp -fopenmp -o auto_reduction
	g++ -O3 manual_own.cpp -fopenmp -o reduction
