# INC=-I/usr/local/cuda/include
# NVCC=/usr/local/cuda/bin/nvcc
# NVCC_OPT=-std=c++11
 
# all:
#     $(NVCC) $(NVCC_OPT) gpu-example.cpp -o gpu-example
# 	$(NVCC) $(NVCC_OPT) new.cu -o new

# clean:
	
#     -rm -f new


all:

# 	g++ -O3 -fopenmp -std=c++11 CUDA_test.cpp -o program
# 	nvcc CUDA_test.cu -o program
	nvcc new.cu -o new

